### ISSUE TITLE
Add UI documentation to website

### ISSUE THREAD

**Issue by wborn** [openremote/Documentation#28]
It would be nice to have UI component documentation using [Storybook](https://storybook.js.org/) on the website.
There is already a [PoC for this](https://github.com/openremote/openremote/tree/feature/ui-docs-temp).

The remaining work includes:

- [ ] Adding documentation for the remaining components
- [ ] Add a task to the Gradle build that generates all the UI documentation
- [ ] The documentation in the PoC currently uses OpenRemote APIs so it requires a running OpenRemote instance. This may cause older documentation to break when there are API changes.
- [ ] The documentation should be made available on the documentation website
- [ ] Preferably when new releases are created the UI documentation is automatically added to the documentation website

**Comment by MartinaeyNL** [comment]
I've split up this Epic to individual issues that are smaller in size.
They do not include all checkboxes given here, but indicate the amount of work left on this.

List of tasks:
- [ ] https://github.com/openremote/openremote/issues/1606
- [ ] https://github.com/openremote/openremote/issues/1607
- [ ] https://github.com/openremote/openremote/issues/1609
- [ ] https://github.com/openremote/openremote/issues/1610
- [ ] https://github.com/openremote/openremote/issues/1611
- [ ] https://github.com/openremote/openremote/issues/1612
- [ ] https://github.com/openremote/openremote/issues/1613
- [ ] https://github.com/openremote/openremote/issues/1614
- [ ] https://github.com/openremote/openremote/issues/1616
- [ ] https://github.com/openremote/openremote/issues/1617

**Comment by MartinaeyNL** [comment]
Removed the UI documentation Epic from the internal projects board.
I'll add the issues described above individually instead.
